### ISSUE TITLE
link:*Error{Condition: amqp:connection:forced, Description: , Info: map[]

### ISSUE THREAD

**Issue by thejams** [Azure/go-amqp#106]
hi im trying to create a sender and a receiver to connect to a amq MQ, im know very little about how ibm mq works, this is how im connecting to the mq and how im trying to create the sender:

```go
client, err := amqp.Dial("amqp://localhost:5672",
		amqp.ConnSASLPlain("app", "passw0rd"),
	)
	if err != nil {
		log.Fatal("Dialing AMQP server:", err)
	}
	defer client.Close()

	// Open a session
	session, err := client.NewSession()
	if err != nil {
		log.Fatal("Creating AMQP session:", err)
	}

	ctx := context.Background()

{

		// Create a sender
		sender, err := session.NewSender(
			amqp.LinkTargetAddress("DEV.QUEUE.1"),
		)
		if err != nil {
			log.Fatal("Creating sender link:", err)
		}

		ctx, cancel := context.WithTimeout(ctx, 5*time.Second)

		// Send message
		err = sender.Send(ctx, amqp.NewMessage([]byte("Hello!")))
		if err != nil {
			log.Fatal("Sending message:", err)
		}

		sender.Close(ctx)
		cancel()
	}
```

in the amqp.LinkTargetAddress("DEV.QUEUE.1"), i tried to put the name of the queue, the name of the queue manager and even the name of the amq channel that i create following ibm instructions, but nothing works, 

with the mq-light library for node js it works just fine, could you help me telling me what im missing ?

**Comment by jhendrixMSFT** [comment]
Were you able to get this to work?  I'm not familiar with IBM MQ.

**Comment by jhendrixMSFT** [comment]
Closing as stale, please ping back if you're still having issues.
