### ISSUE TITLE
Consider wrapping the error returned when the remote service is at fault

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/go-amqp#109]
Currently if the remote sender does something that's incorrect for the protocol we send them a `ErrorNotAllowed`, which makes sense. 

However, we also return this error back to the local caller. This seems like one of those cases where we should consider marking this as an internal error instead, so it's clear that this is not something is incorrect on the client-side.

We can still preserve the context of the error, this would merely wrap the original error in a more sensible casing.

**Comment by jhendrixMSFT** [comment]
`amqp.ErrNotAllowed` is an error condition value, and we do return these in an `amqp.Error` type, so I think we're doing the correct thing here.  Please reopen if you disagree.
