### ISSUE TITLE
Support the amqp+ssl scheme

### ISSUE THREAD

**Issue by octomad** [Azure/go-amqp#118]
Request to add the `amqp+ssl` scheme. This appears to be the same as the `amqps` scheme that is already supported. If you want a PR for this I can submit one. This is so that it will be compatible with ActiveMQ AMQP over SSL.

https://activemq.apache.org/amqp

**Comment by octomad** [comment]
Do you want a PR for this?

**Comment by jhendrixMSFT** [comment]
Fixed in v0.17.3
