### ISSUE TITLE
Long messages and "Servicebus Lock Duration"

### ISSUE THREAD

**Issue by Zenlil** [Azure/go-amqp#12]
We are experiencing weird behaviour when messages take longer than half the lock-duration of the servicebus queue or topic.

Example:
Queue with a lock-duration of 30 seconds
All messages taking 20 seconds before Accept.

Expected behaviour:
All messages to be read and accepted by the servicebus

Actual behaviour:
1st message gets accepted correctly by the queue
all subsequent messaged are reported to the client as accepted, but the queue handles them like "Release()"
i.e no errors are reported from the "msg.Accept()"-call

The timing is always half of the "lock-duration", i.e setting lock-duration to max 5 minutes, messages taking >2.5 minutes behave the same as the scenario above.
and all messages taking less than half the lock-duration works as they should.

after some extended testing it seems that some message occasionally gets accepted correctly, but most messages end up as "released"

**Comment by serbrech** [comment]
I'm pretty sure we can close this now :)

**Comment by jhendrixMSFT** [comment]
This should be fixed in `v0.13.2`
