### ISSUE TITLE
Validate if we need to auto-accept messages explicitly in modeFirst

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/go-amqp#124]
Currently go-amqp calls .Accept() on messages received in ModeFirst.

From our reading of the spec it's possible we don't need to do that, which can be beneficial to callers because it removes a bit of I/O in that path (and removes a potential point of failure for no gain).

This is mostly just a "check that our behavior matches other reference implementations" issue.

**Comment by serbrech** [comment]
I remember digging in .net implementation, which was doing the same. I don't have the link handy though.

**Comment by richardpark-msft** [comment]
Just ran through the debugger on this, it's an interesting trace :)

Long story short, it looks like we don't need to call Accept(). 

The delivery for the message, when it arrives, already has 'settle' set to true. After winding through all of the code you eventually end up in AmqpSession::DisposeDelivery, where it short-circuits and exits if you've already settled the message:

```csharp
// from AmqpSession.cs
// (delivery.Settled here is already true as it comes from the incoming message)
public void DisposeDelivery(Delivery delivery, bool settled, DeliveryState state, bool noFlush) 
{
  if (delivery.Settled)
  {
// NOTE: we end up returning here.
    this.OnWindowMoved(1);
    return;
  }

// code that would have actually sent a disposition
```

So we don't need to do this in our code for modeFirst. I'll submit a PR in a moment.

(I've also tested this with azservicebus and receiveAndDelete, and it continues to work without the .Accept() calls in place).

**Comment by mgevantmakher** [comment]
Would you pls tag a next release version that includes this commit, this is an important bug fix as it prevents an unwanted auto ack in ModeFirst.

**Comment by jhendrixMSFT** [comment]
@mgevantmakher sorry for the delay.  Tagged `v0.17.5`
