### ISSUE TITLE
Accepting disposition hangs if the link is close()d

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/go-amqp#126]
While testing azservicebus it looks like if the link is closed calling 'accept()' will hang, rather than returning a more relevant error (ex: ErrLinkClosed).

This is partly investigation, as @jhendrixMSFT did have code to handle this case [(code)](https://github.com/Azure/go-amqp/blob/master/receiver_test.go#L996-L999)

**Comment by richardpark-msft** [comment]
I just figured this one out, PR incoming!

**Comment by mcardy** [comment]
I'm hitting this issue on 0.17.5. Can we tag 0.17.6 with this fix @jhendrixMSFT?

**Comment by mgevantmakher** [comment]
@richardpark-msft I'm also hitting it, pls tag a release with this fix

**Comment by richardpark-msft** [comment]
@mgevantmakher, this is the internally vendored copy of go-amqp. Are you looking for this fix to appear in the Service Bus package (ie: azservicebus) or in go-amqp itself?

If it's within azservicebus, the latest version of azservicebus already contains this fix.
