### ISSUE TITLE
amqp:session:invalid-field, Description: sequencing error, expected delivery-id X, got Y

### ISSUE THREAD

**Issue by tymonx** [Azure/go-amqp#135]
I got this when trying to running two or more AMQP receivers in separate process (executables) with the [Apache Qpid Dispatch Router](https://qpid.apache.org/components/dispatch-router/index.html). It works fine with the [Qpid Electron](https://github.com/apache/qpid-proton/tree/main/go/pkg) Go package. Also no issues with only one AMQP receiver. But this is not usable.

```
*Error{Condition: amqp:session:invalid-field, Description: sequencing error, expected delivery-id 3, got 4, Info: map[]}
```

**Comment by jhendrixMSFT** [comment]
Sorry for the late reply.

Were you able to find a solution or work around this?  I ask because we've had another bug report when running under qpid-dispatch.

**Comment by jhendrixMSFT** [comment]
Fixing in pending release `v0.18.1`
