### ISSUE TITLE
Can't set settlement mode to anything but default mixed mode

### ISSUE THREAD

**Issue by aneeshkp** [Azure/go-amqp#17]
Setting settlement mode to ModeSettled error out.

`Creating sender link:amqp: sender settlement mode "settled" requested, received "mixed" from server`

```
sender, err := session.NewSender(
			amqp.LinkTargetAddress("/queue-name"),amqp.LinkSenderSettle(amqp.ModeSettled),
		)
		```

**Comment by serbrech** [comment]
Hi @aneeshkp which broker are you using. 

This means that although you send "Settled", the broker your are using is informing you that the target address you created is "mixed". the library checks for that and errors.

**Comment by serbrech** [comment]
As I said above, I believe that the error is due to the peer answering you with a different setting than what you request.

**Comment by jhendrixMSFT** [comment]
As noted, the error message indicates a mismatch between the client and the broker; this is not a bug.

You can still call `Recevice()`, we will be removing its deprecated status in a future update.
