### ISSUE TITLE
The initial deliveryID for a msg is 1 not 0

### ISSUE THREAD

**Issue by atyronesmith** [Azure/go-amqp#18]
https://github.com/Azure/go-amqp/blob/6a20a079aa598260ec97857517635d5b02a20b6a/client.go#L395

When starting a link, the receiver sends a flow message expecting next next-deliver-id == 0,
but the send code starts with deliveryID = 1.  

This causes the receive client to not acknowledge the second msg that is sent.

**Comment by serbrech** [comment]
Hi, thanks for reporting this.

By curiosity, where are you using `go-amqp`, and how did you notice this?
I think most people have used it as receiver, and that's why it wasn't noticed before.

Will take a look into this, unless you want to send a PR?

**Comment by atyronesmith** [comment]
Hi,
  I was meaning to close this issue...  The deliveryID does start at 2, but after rereading the AMQP1 spec, this is ok.  The problem we were experiencing was due to how we were using the Client, not the client itself.  I noticed the deliveryID start
point using wireshark and following an AMQP sequence.  Wireshark has support for AMQP decoding which made it easy to see.

Thank you.
