### ISSUE TITLE
Non-variadic receiver config no longer allows creating "durable" subscriptions

### ISSUE THREAD

**Issue by imirkin** [Azure/go-amqp#191]
I'm connecting to an IBM MQ server. In the old universe, we had:

```go
session.NewReceiver(
  amqp.LinkSourceAddress(...),
  amqp.LinkSourceExpiryPolicy(amqp.ExpiryLinkDetach),
  amqp.LinkSourceTimeout(86400*365*5))
```

This would create a durable subscription on the IBM MQ server, i.e. the named subscription would stick around even after a disconnect. This would allow messages to get added to this subscription on arrival, essentially using it for storage of the messages to be processed. This is (or at least was) a recommended way of integrating AMQP into the IBM MQ universe.

However with the new-style non-variadic configs, only `link.Target` things are settable, so this becomes an ephemeral subscription and non-durable queue.

It would be ideal if we could continue to do this.

**Comment by jhendrixMSFT** [comment]
To clarify, are you saying with the recent changes to _remove_ variadic config that we can no longer create durable subscriptions?

**Comment by imirkin** [comment]
Yes, sorry. I thought the new one was variadic without giving the name too much thought. Obviously the old one was. Will edit description to match.

**Comment by imirkin** [comment]
For reference, here is some information on IBM MQ's AMQP support:

https://www.ibm.com/docs/en/ibm-mq/9.3?topic=applications-amqp-10-support
https://www.ibm.com/docs/en/ibm-mq/9.3?topic=tacm-amqp-client-using-queue-alias-receive-messages-from-mq-application
https://www.ibm.com/docs/en/ibm-mq/9.3?topic=tacm-configuring-amqp-clients-interact-directly-applications-mq-queues

[And don't ask the obvious question of "why use IBM MQ", it's a sad tale of interop.]

**Comment by imirkin** [comment]
I left a note on the pull request as well, but with IBM MQ 9.3, it's now possible to attach to a queue directly (yay). This is done with capabilities:

https://www.ibm.com/docs/en/ibm-mq/9.3?topic=applications-amqp-10-support

and these capabilities need to be on the source as well, not the target.
