### ISSUE TITLE
how do i authenticate with service bus queue using primary key?

### ISSUE THREAD

**Issue by geekyarthurs** [Azure/go-amqp#24]
I need a small snippet please.

**Comment by jhendrixMSFT** [comment]
Take a look at [`cbs.NegotiateClaim()`](https://github.com/Azure/azure-amqp-common-go/blob/master/cbs/cbs.go#L50)`, which is what our service bus package uses to [authenticate](https://github.com/Azure/azure-service-bus-go/blob/master/namespace.go#L248).

**Comment by jhendrixMSFT** [comment]
Closing as I believe this has been answered.
