### ISSUE TITLE
[Discussion] Receiver and Session interaction with windows and credits

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/go-amqp#240]
This is a discussion about a design change to eliminate the fixed-size channel that Receivers use for storing messages.

The basic problem is that Receivers take a maximum credit value as part of their initialization. That value is used to size the underlying channel that holds onto messages that have been funneled through the session to our individual receiver. This is an arbitrary restriction - theoretically a person should be able to request as many credits as they want. 

The session will enforce it's window, preventing an excess of concurrent TRANSFER frames, but the Receiver should be able to absorb them quickly, and into it's own internal buffer. 

There are some other complications to doing this, but once this is changed it'll simplify life for callers since they can control their capacity by managing their credits, rather than having to determine everything statically.

**Comment by jhendrixMSFT** [comment]
fix will be in `v0.19.0`
