### ISSUE TITLE
`GetData()` only returns the first data segment

### ISSUE THREAD

**Issue by deissnerk** [Azure/go-amqp#325]
An AMQP message may contain multiple data sections, but `GetData()` only returns the first. [We discussed this](https://github.com/cloudevents/spec/issues/1275) in the context of the [CloudEvents AMQP binding](https://github.com/cloudevents/spec/blob/main/cloudevents/bindings/amqp-protocol-binding.md) and concluded that all data sections need to be concatenated. Is there a reason for only returning the first segment?
https://github.com/Azure/go-amqp/blob/1003610b1e679a884a60f9011c37e55c6eb07338/message.go#L125

**Comment by jhendrixMSFT** [comment]
It was a helper used by our old event hubs and service bus SDKs. Removing/changing it would have been a breaking change, so we left it as-is.

It's best to just directly access the [`Data`](https://github.com/Azure/go-amqp/blob/main/message.go#L88) field.

**Comment by deissnerk** [comment]
Thank you @jhendrixMSFT
