### ISSUE TITLE
Connecting to ActiveMQ Classic v6.1.1 fails

### ISSUE THREAD

**Issue by SamTV12345** [Azure/go-amqp#328]
I try to use your sdk to connect to ActiveMQ and read and write messages. Unfortunately ActiveMQ does not allow a connection. It says

 WARN | Connection attempt from non AMQP v1.0 client. AMQP,0,1,0,0

I used:
 ```go
	conn, err := amqp.Dial(context.Background(), "amqp://localhost:5672", nil)
```

**Comment by SamTV12345** [comment]
Found the error. For whatever reason ActiveMQ declines the connection and shows this generic message. There is no version conflict. You just need to have the SASLType set. I set mine to:

	conn, err := amqp.Dial(context.Background(), "amqp://localhost:5672", &amqp.ConnOptions{
		SASLType: amqp.SASLTypeAnonymous(),
	})

**Comment by ansd** [comment]
Nice! The client needs to start the handshake with `AMQP,2,1,0,0` where the `2` means SASL security layer.
(The SASL security layer is also required in RabbitMQ 4.0 btw.)
