### ISSUE TITLE
How to efficiently send multiple messages at once?

### ISSUE THREAD

**Issue by ansd** [Azure/go-amqp#331]
I would like to send 10,000 messages in one batch on a given link with Sender Settle Mode `unsettled` and Receiver Settle Mode `first`.
After all 10,000 messages are confirmed by the broker, I would like to send the next batch.

Do I understand correctly, that with this library, I have to create 10,000 different goroutines to achieve this?

**Comment by jhendrixMSFT** [comment]
The short answer is yes. Now that said, in `azservicebus` we have the ability to send [message batches](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azservicebus/message_batch.go). However, this might be specific to how Service Bus works thus not a general-purpose mechanism. I'll defer to @richardpark-msft on the answer here as he implemented batching for SB.

**Comment by richardpark-msft** [comment]
@ansd, this one sent me down a little rabbit hole. :)

The way this works in Service Bus and Event Hubs is (from what I can I tell) specific to those services. I don't see a "standard" way to do this same thing.

This is the code for it in Service Bus, in case you want to give it a shot - it's pretty much only using primitives available in go-amqp, so you should be able to transplant it to your project: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azservicebus/message_batch.go#L124

Just curious, what AMQP service are you using for this? There might be something specific to that broker that allows it.

**Comment by ansd** [comment]
Thank you for your replies @jhendrixMSFT and @richardpark-msft :) 

> Just curious, what AMQP service are you using for this?

I'm using RabbitMQ.

The word "batch" that I used might have been a misnomer.

My goal is sending many (different) messages using this Go lib one after another on the same link while having each message being confirmed by the broker later on. I was mainly surprised that I have to open a separate goroutine for each message that I send. I know that goroutines in general are efficient and have a small overhead. However, creating one goroutine per message does not sound performant. (Although I have to admit, I haven't benchmarked the overhead on the client lib side.) The [AMQP 0.9.1 Golang client](https://github.com/rabbitmq/amqp091-go) can send multiple messages (in confirm mode) without blocking the caller.

**Comment by jhendrixMSFT** [comment]
Thanks for clarifying.

I see, they have a method `PublishWithDeferredConfirm` so that callers don't immediately block waiting for message settlement. Unfortunately, we don't have something similar at present, so any concurrency will have to be written by callers. Agreed that this isn't optimally performant.

We can consider adding such a feature but given current priorities, it would be pretty low, so I don't know when we'd actually get to it (we can keep this issue open to track it).

**Comment by ansd** [comment]
Thank you! Yes, let's keep this issue open.
If this feature becomes important for us (Team RabbitMQ), we might consider adding a PR in the future.

**Comment by jhendrixMSFT** [comment]
This has been released in `v1.4.0-beta.1`.
