### ISSUE TITLE
Is it possible to connect to multiple Artemis instances?

### ISSUE THREAD

**Issue by DanilKlochkov** [Azure/go-amqp#338]
In Java you can set property e.g. spring.artemis.url=(tcp://host:61616,tcp://host2:61616), and your client manages connections itself. I need to rewrite some services from Java to Golang, but I can't find a library supports connection to multiple nodes.

**Comment by jhendrixMSFT** [comment]
Not with a single `Conn` instance, you'd have to create one instance per connection.

**Comment by jhendrixMSFT** [comment]
Closing. Please ping back if you have further questions.
