### ISSUE TITLE
Could not create new client using IP address

### ISSUE THREAD

**Issue by mumumik** [Azure/go-amqp#34]
Hi, 

I'm facing an issue when I tried to create a new client using **New(conn net.Conn, opts ...ConnOption)** function and the host that I'm currently using is IP address. Here are some code with dummy values:

```
conn, err := net.Dial("tcp", "10.10.10.10:61616")
client, err := amqp.New(conn, amqp.ConnServerHostname("10.10.10.10"), amqp.ConnSASLPlain("username, "password"), amqp.ConnIdleTimeout(0))
if err != nil {
	log.Fatal("Dialing AMQP server: ", err)
}
```

I got this in the response
`
"Dialing AMQP server: invalid frame body header"
`

Any advice on this? 
Thank you

**Comment by jhendrixMSFT** [comment]
@mumumik sorry for the delay.  Were you able to resolve your issue?

**Comment by jhendrixMSFT** [comment]
Closing as stale.  Please ping back if still an issue.
