### ISSUE TITLE
Feature request: Expose a send with the Outcome Delivery State

### ISSUE THREAD

**Issue by Gsantomaggio** [Azure/go-amqp#347]
Problem:
---
The API [Send(..)](https://github.com/Azure/go-amqp/blob/main/sender.go#L68) hides the [Outcome Delivery state ](https://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-messaging-v1.0-os.html#section-delivery-state), which is fine for most use cases. 

In RabbitMQ we'd need to expose all the states to the user, for example: [`RELEASED`](https://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-messaging-v1.0-os.html#type-released)  means:

> RabbitMQ could not route the message to any queue. This indicates a topology misconfiguration,

see: https://www.rabbitmq.com/docs/next/amqp#outcomes

Proposal:
---

Another API with more control, like exposing the private [send()](https://github.com/Azure/go-amqp/blob/main/sender.go#L102)
It would be:
```golang
func (s *Sender) SendWithOutCome(ctx context.Context, msg *Message, opts *SendOptions) (chan encoding.DeliveryState, error) {
	select {
	case <-s.l.done:
		return s.l.doneErr
	default:
		// link is still active
	}
	return s.send(ctx, msg, opts)
}
```

In this way, there is complete control of the delivery outcome state. 

Notes:
--- 
The .NET client has [access to this information](https://github.com/Azure/amqpnetlite/blob/cfc6154cd623846a0486f586a2228b8cc73bb668/src/Framing/Released.cs#L25)

So the information is accessible to the user, [see our example](https://github.com/rabbitmq/rabbitmq-amqp-dotnet-client/blob/main/docs/Examples/GettingStarted/Program.cs#L67-L80) 

Please let me know what you think. I can prepare a PR for that. 
Thank you

**Comment by jhendrixMSFT** [comment]
I've sketched out a potential solution for this. It also includes the change for sending with deferred confirmation of settlement.

The API is [`SendWithReceipt()`](https://github.com/jhendrixMSFT/go-amqp/blob/send-receipt/sender.go#L173) which returns a new [`SendReceipt`](https://github.com/jhendrixMSFT/go-amqp/blob/send-receipt/sender.go#L112) type that's used to [`Wait()`](https://github.com/jhendrixMSFT/go-amqp/blob/send-receipt/sender.go#L136) for confirmation of settlement and returns one of the concrete [`DeliveryState`](https://github.com/jhendrixMSFT/go-amqp/blob/send-receipt/delivery_state.go#L12) types. It's kind of like a "power user" version of `Send()`.

I haven't had a chance to discuss this with @richardpark-msft yet so it might change but any early feedback would be great.

**Comment by Gsantomaggio** [comment]
Thank you, @jhendrixMSFT it looks good to me

**Comment by richardpark-msft** [comment]
@jhendrixMSFT , is there a particular reason we can't just block in `SendWithReceipt()` so the caller doesn't need to call Wait()?

**Comment by jhendrixMSFT** [comment]
The addition of `Wait()` is in response to https://github.com/Azure/go-amqp/issues/331 (i.e. this sketch fixes both issues).

**Comment by richardpark-msft** [comment]
> The addition of `Wait()` is in response to [#331](https://github.com/Azure/go-amqp/issues/331) (i.e. this sketch addresses both issues).

Makes sense.

I did notice one annoying case with Wait(). If you're dealing with the `Rejected` outcome, you'd need to check two places in order to know if there's a failure - the 'error' return value _and_ within the Rejected outcome itself. For simplicity, we could make it so `Wait()` also does the same "Rejected.Error" logic, like we do for Send() [(link)](https://github.com/jhendrixMSFT/go-amqp/blob/bc57fcdf55f031c9355e532ad6bfcc98b471ed53/sender.go#L101).

A second, smaller thing, is `DeliveryState`, and it's children, are internal now, so now we'll have to doc them. 

Otherwise, I think this all looks good.

**Comment by richardpark-msft** [comment]
@jhendrixMSFT, yes, agreeing with you about the current behavior. Do we want it to _also_ do the same thing as Send() so it still feels like the same logic, just "disconnected"?

**Comment by jhendrixMSFT** [comment]
I'd prefer to return the `*StateRejected` outcome so it's consistent with the other outcomes. It also works nicely in a type switch statement, so one can handle all possible outcomes in one place.

**Comment by richardpark-msft** [comment]
That's reasonable. I think it's worth documenting, maybe on Wait() itself, that this behavior is different than the Send() behavior.

**Comment by jhendrixMSFT** [comment]
This has been released in `v1.4.0-beta.1`.

**Comment by Gsantomaggio** [comment]
Thank you @jhendrixMSFT

**Comment by jhendrixMSFT** [comment]
Let us know how the new features work and if you encounter any bugs.

Given the upcoming US holiday, I doubt this will make it out of beta until Jan (just FYI).

**Comment by Gsantomaggio** [comment]
Happy New Year all :)
I could not try the version due to other tasks. I hope to test it within the end of the month. 
Sorry for the delay.

**Comment by Gsantomaggio** [comment]
It works correctly. I did different tests, and for the moment, there are no problems! thanks a lot!

**Comment by jhendrixMSFT** [comment]
Fantastic, thanks for testing it and reporting back.
