### ISSUE TITLE
Is this lib Fully AMQP 1.0 complaint?

### ISSUE THREAD

**Issue by hariyada** [Azure/go-amqp#350]
Hi All, is this library fully AMQP 1.0 complaint? if it is partial which features are missing? I got this doubt since some of the forums say it is Light-weight and minimalistic AMQP 1.0 client for Go.

eg: ![Image](https://github.com/user-attachments/assets/29341d81-1131-494f-a80c-6b2356b60049)

**Comment by jhendrixMSFT** [comment]
While we do follow the 1.0 spec, there are some features that have not been implemented.
- suspending/resuming links
- detaching/reattaching links
- transactions

The Azure Event Hubs and Service Bus SDKs are both built on top of this module.

**Comment by jhendrixMSFT** [comment]
Closing. Please ping back if you have further questions.
