### ISSUE TITLE
Any support to Renew message locks?

### ISSUE THREAD

**Issue by emuslor** [Azure/go-amqp#354]
I'm looking for an example of how one could implement the RenewLockAsync functionality that exists in some APIs for maintaining locks on Azure Service Bus queue items to prevent long-running processors from losing their locks and messages being requeued.  ASB max lock time is 5 minutes.  My understanding is one can either set AutoRenewTimeout to a large enough timeout or periodically renew the lock manually as a task runs long.

**Comment by jhendrixMSFT** [comment]
There's the [`azservicebus`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus) SDK specifically for working with ASB and their implementation of renew lock can be found [here](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azservicebus/receiver.go#L301-L316). However, there is no support for batch renew locks yet (see https://github.com/Azure/azure-sdk-for-go/issues/23807).

The `go-amqp` module is broker agnostic so there would be no support in it that's specific to ASB.

**Comment by emuslor** [comment]
Thanks for the quick response.  Then, to deal with this when using AMQP (because we also want to be broker-agnostic), we'll just need to make sure we can get out of processing before the timeout and deal with saving and picking the work back up gracefully when necessary.  I guess I was hoping perhaps there was some generic mechanism that could be used to send that request, but I also am not an AMQP expert.

**Comment by jhendrixMSFT** [comment]
Well, you _could_ copy the renew locks implementation from `azservicebus`. However, I don't know if the inner workings are publicly documented so it might just cause future headaches (e.g. something changes, things don't work as expected, etc).

@richardpark-msft does SB publicly document how renewing locks works?

**Comment by jhendrixMSFT** [comment]
Thinking more about this, it _has_ to be documented somewhere (compliance etc).

**Comment by richardpark-msft** [comment]
@emuslor, for documentation, at the AMQP level you're looking for this: https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-request-response#message-renew-lock

There's not a lot of configurability for that operation, so it might not be worth the trouble to go to the AMQP level, nor can you really be broker-agnostic as this is a Microsoft specific operation.

Let's go back to the original question though:

> I'm looking for an example of how one could implement the RenewLockAsync functionality that exists in some APIs for maintaining locks on Azure Service Bus queue items to prevent long-running processors from losing their locks and messages being requeued. ASB max lock time is 5 minutes. My understanding is one can either set AutoRenewTimeout to a large enough timeout

The amount of time the lock is renewed for is not configured in the lock renewal call, but at the queue/subscription level, as part of the parameters configured in ARM. So if your goal is to just increase the "time extended per renewlock call" you can change it there, and it'll be reflected in the expiration time returned by the renew lock operation.

> or periodically renew the lock manually as a task runs long.

This is the typical way, and it's just a loop around your RenewLock equivalent, checking for azservicebus.CodeLockLost. We have an example of this in azservicebus, if you want to use that package: https://github.com/Azure/azure-sdk-for-go/blob/ff4135cae625936950ca81229d5c59496ffe5e41/sdk/messaging/azservicebus/example_client_autoRenewLocks_test.go#L23

Closing this issue, as this isn't something that would go into a broker-agnostic library like go-amqp.

**Comment by emuslor** [comment]
Thanks for the additional info.  I'm already configuring the queue for max ASB lock time of 5 minutes and wouldn't want to go any larger anyway and end up with unprocessed items not coming back around to retry for a long time.  It's just my goal to be able to renew my lock for another 5 minutes in the case that processing is going to take longer with very little knowledge of (and dealing with) the underlying ASB implementation.  Based on these answers and needing to using the service-bus package, it seems that's just not going to happen.
