### ISSUE TITLE
Don't disconnect the link on message disposition errors

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/go-amqp#45]
Test against Service Bus and Event Hubs

- [ ] Don't detach on disposition errors
- [ ] Test against Event Hubs with throttling
- [ ] Test against Service Bus with something like message lock expired

**Comment by jhendrixMSFT** [comment]
This was added in https://github.com/vcabbage/amqp/pull/50.

**Comment by richardpark-msft** [comment]
This was fixed in https://github.com/Azure/go-amqp/pull/47
