### ISSUE TITLE
Add SEQUENCE section encoding to amqp.Message

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/go-amqp#94]
There are three sections you can use to encode data into an AMQP message:
- Value (typed as interface{})
- Data (typed as [][]byte)
- Sequence (squashed into Data)

Sequence can actually be a sequence of several types of things, not just []bytes, and (like .Value) should be it's own separate field, with it's own distinct type.

My proposal is to create a .Sequence property and type it as []interface{}.

(The 'squashed' part is based on this comment in the code:)

```go
// in Message

Data [][]byte
// A data section contains opaque binary data.
// TODO: this could be data(s), amqp-sequence(s), amqp-value rather than single data:
// "The body consists of one of the following three choices: one or more data
//  sections, one or more amqp-sequence sections, or a single amqp-value section."
```

**Comment by serbrech** [comment]
As long as that doesn't break anything to handle in-transit messages upon update of the library, I'm all for it.
Should be fine as whatever is on the wire is still the same.

What is the reasoning behind typing it as interface, instead of []byte?
What will be the actual type behind it?

**Comment by richardpark-msft** [comment]
> As long as that doesn't break anything to handle in-transit messages upon update of the library, I'm all for it. Should be fine as whatever is on the wire is still the same.

I'm not sure if I understand what you mean here.

> 
> What is the reasoning behind typing it as interface, instead of []byte? What will be the actual type behind it?

It's a sequence of AMQP types, so it's basically like having a list of '.Value' fields (which is an interface{} for the same reason from what I can tell).
